# Generated by Django 4.2.5 on 2023-09-27 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_advertisements', '0006_alter_advertisement_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='advertisement',
            name='image',
            field=models.ImageField(default='', upload_to='advertisements/images', verbose_name='Изображение'),
            preserve_default=False,
        ),
    ]
